# Schema for the configuration files of the Comment Alter module.

field.field.*.*.*.third_party.comment_alter:
  type: mapping
  label: 'Comment alter field settings'
  mapping:
    altering_enabled:
      type: boolean
      label: 'Comment alter enabled for the field'
    hide_alteration:
      type: boolean
      label: 'Hide alterations of the field from diffs'
